<?php
/**
 * BTW IMF blog admin — one-time setup. Creates admin/config.php.
 * Refuses to run once configured. Delete or ignore afterwards.
 */
declare(strict_types=1);
require_once __DIR__ . '/lib.php';

if (is_configured()) { header('Location: index.php'); exit; }

$err = '';
$done = false;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $pw   = (string)($_POST['password'] ?? '');
    $pw2  = (string)($_POST['password2'] ?? '');
    $site = rtrim(trim((string)($_POST['site_url'] ?? 'https://btwimf.com')), '/');
    if (strlen($pw) < 10)                 $err = 'Use a password of at least 10 characters.';
    elseif ($pw !== $pw2)                 $err = 'The two passwords do not match.';
    elseif (!preg_match('#^https?://[^/\s]+$#', $site)) $err = 'Enter a valid site URL, e.g. https://btwimf.com';
    else {
        $sample = require __DIR__ . '/config.sample.php';
        $cfg = array_merge($sample, [
            'site_url' => $site,
            'password_hash' => password_hash($pw, PASSWORD_DEFAULT),
        ]);
        $php = "<?php\n// Generated by admin/setup.php on " . date('c') . ". Keep this file private.\nreturn " . var_export($cfg, true) . ";\n";
        if (@file_put_contents(CONFIG_FILE, $php, LOCK_EX) === false) {
            $err = 'Could not write admin/config.php — check that the admin/ folder is writable, or create the file manually from config.sample.php.';
        } else {
            $done = true;
        }
    }
}
?><!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Set up · BTW IMF Blog Admin</title>
<link rel="stylesheet" href="assets/admin.css">
</head><body class="admin-auth">
<div class="auth-card">
  <div class="admin-brand"><span>BTW IMF</span> Blog Admin</div>
  <?php if ($done): ?>
    <h1>All set</h1>
    <p class="ok">Configuration saved. You can now sign in.</p>
    <p style="margin-top:8px"><em>For safety, delete <code>admin/setup.php</code> from the server.</em></p>
    <a class="btn" href="index.php">Go to sign in</a>
  <?php else: ?>
    <h1>First-time setup</h1>
    <p>Choose an admin password. It is stored only as a secure hash.</p>
    <?php if ($err): ?><p class="err"><?= h($err) ?></p><?php endif; ?>
    <form method="post" autocomplete="off">
      <label>Site URL
        <input type="url" name="site_url" value="<?= h($_POST['site_url'] ?? 'https://btwimf.com') ?>" required>
      </label>
      <label>Password
        <input type="password" name="password" minlength="10" required>
      </label>
      <label>Confirm password
        <input type="password" name="password2" minlength="10" required>
      </label>
      <button class="btn" type="submit">Save configuration</button>
    </form>
  <?php endif; ?>
</div>
</body></html>
